name: daily_draws_viewer
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  dama:
    git:
      url: git://github.com/thumbert/dama.git
  date:
    git:
      url: git://github.com/thumbert/date.git
  elec_server:
    git:
      url: git://github.com/thumbert/elec-server.git
  http: '>=0.12.0 <0.20.0'
  plotly:
    git:
      url: git://github.com/thumbert/plotly.git
  table:
    git:
      url: git://github.com/thumbert/table.git
  timeseries:
    git:
      url: git://github.com/thumbert/timeseries.git
  timezone: '>=0.5.5 <1.0.0'


dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  test: ^1.14.1
