name: load_viewer
description: Load shapes
version: 0.0.1
#homepage: https://www.example.com
#author: tony <email@example.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  dama:
    git:
      url: git://github.com/thumbert/dama.git
  date:
    git:
      url: git://github.com/thumbert/date.git
  elec:
      git:
        url: git://github.com/thumbert/elec.git
  elec_server:
    git:
      url: git://github.com/thumbert/elec-server.git
  http: '>=0.11.1 <0.14.0'
  plotly:
    git:
      url: git://github.com/thumbert/plotly.git
  table:
    git:
      url: git://github.com/thumbert/table.git
  timeseries:
    git:
      url: git://github.com/thumbert/timeseries.git
  timezone: '>=0.5.0-dev-3 <1.0.0'


dev_dependencies:
  build_runner: '>=1.3.0 <2.0.0'
  build_web_compilers: '>=1.2.0 <3.0.0'
  test: '>=1.0.0 <=2.0.0 '